---
# - name: "Provision a Docker engine"
#   hosts: all
#   become_user: root
#   become: yes
#   roles:
#     - docker

- hosts: all
  become_user: root
  become: yes
  roles:
    - docker
  post_tasks:
    - name: pausing for docker restart
      pause:
        minutes: 1
