---
- name: master-setup
  hosts: node1
  become_user: "{{ redis_user }}"
  become: yes
  vars:
    conf_type: "{{ redis_master }}"
  roles:
    - redis_ha_cluster
  tags: master

- name: slave-setup
  hosts: node2 node3
  become_user: "{{ redis_user }}"
  become: yes
  vars:
    redis_slaveof: 192.168.10.11 6379
  roles:
    - redis_ha_cluster
  tags: slave

- name: sentinel-setup
  hosts: node4 node5
  become_user: "{{ redis_user }}"
  become: yes
  vars:
    - redis_sentinel: True
    - redis_sentinel_monitors:
       - name: mymaster
         host: 192.168.10.11
         port: 6379
  roles:
    - redis_ha_cluster
  tags: Sentienel
